<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'An unsupported grant type was requested.' => '',
    'An unsupported response type was requested.' => '',
    'Authorization code is missing.' => '',
    'Client secret' => '',
    'Invalid or missing response type.' => '',
    'Invalid server state or the User Session has expired.' => '',
    'Invalid username or password.' => '',
    'OAuth2IdentityInterface is not implemented.' => '',
    'Only one method may be used to authenticate at a time (Auth header, POST or GET).' => '',
    'Redirect URI used for Authorization Grant' => '',
    'Space-delimited list of approved scopes' => '',
    'Space-delimited list of grant types permitted, null = all' => '',
    'The Refresh Token is invalid.' => '',
    'The User denied access to your application.' => '',
    'The access token does not have required scopes.' => '',
    'The access token provided has expired.' => '',
    'The access token provided is invalid.' => '',
    'The access token was not found.' => '',
    'The authorization code is not found or has been expired.' => '',
    'The client credentials are invalid.' => '',
    'The content type for POST requests must be "application/x-www-form-urlencoded".' => '',
    'The grant type was not specified in the request.' => '',
    'The redirect URI provided does not match.' => '',
    'The redirect URI provided is missing or does not match.' => '',
    'The request is missing "refresh_token" parameter.' => '',
    'The requested scope is invalid, unknown, or malformed.' => '',
    'Unable to create access token.' => '',
    'Unable to create authorization code.' => '',
    'Unable to create refresh token.' => '',
    'Unique client identifier' => '',
    'Unknown client.' => '',
    'User is not found.' => '',
    'When putting the token in the body, the method must be POST.' => '',
    'You are requesting with an invalid credential.' => '',
];
